"""
Report Generator
Merges static analysis + LLM findings into a structured JSON audit report.
Computes overall risk score and severity breakdown.
"""

import time
from datetime import datetime, timezone
from typing import Optional

SEVERITY_SCORE = {
    "CRITICAL": 40,
    "HIGH": 20,
    "MEDIUM": 8,
    "LOW": 2,
    "INFO": 0,
}

SEVERITY_ORDER = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]


class ReportGenerator:
    def generate(
        self,
        contract_address: str,
        static_findings: list[dict],
        ai_findings: list[dict],
        duration_seconds: float,
        agent_version: str,
        metadata: Optional[dict] = None
    ) -> dict:
        all_findings = static_findings + ai_findings

        # Deduplicate by category + description similarity (simple hash)
        all_findings = self._deduplicate(all_findings)

        # Compute severity counts
        counts = {sev: 0 for sev in SEVERITY_ORDER}
        for f in all_findings:
            sev = f.get("severity", "INFO").upper()
            if sev in counts:
                counts[sev] += 1

        # Compute numeric risk score (capped at 100)
        raw_score = sum(
            SEVERITY_SCORE.get(f.get("severity", "INFO").upper(), 0)
            for f in all_findings
        )
        risk_score = min(raw_score, 100)

        # Determine overall risk level
        if counts["CRITICAL"] > 0:
            overall_risk = "CRITICAL"
        elif counts["HIGH"] > 0:
            overall_risk = "HIGH"
        elif counts["MEDIUM"] > 0:
            overall_risk = "MEDIUM"
        elif counts["LOW"] > 0:
            overall_risk = "LOW"
        else:
            overall_risk = "SAFE"

        # Build report
        report = {
            "schema_version": "1.0",
            "report_type": "smart_contract_security_audit",
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "agent_version": agent_version,
            "duration_seconds": round(duration_seconds, 2),
            "target": {
                "contract_address": contract_address,
                "chain": "0G",
                "scan_type": "source_code" if any(
                    f.get("source") == "slither" for f in all_findings
                ) else "bytecode"
            },
            "summary": {
                "overall_risk": overall_risk,
                "risk_score": risk_score,
                "total_findings": len(all_findings),
                "findings_by_severity": counts,
                "static_findings_count": len(static_findings),
                "ai_findings_count": len(ai_findings),
            },
            "findings": sorted(
                all_findings,
                key=lambda f: SEVERITY_ORDER.index(
                    f.get("severity", "INFO").upper()
                    if f.get("severity", "INFO").upper() in SEVERITY_ORDER else "INFO"
                )
            ),
            "recommendations": self._generate_recommendations(all_findings),
            "disclaimer": (
                "This report was generated by an AI security agent. "
                "It should be used as a first-pass screening tool, not a replacement "
                "for a full manual audit by qualified security professionals."
            )
        }

        if metadata:
            report["metadata"] = metadata

        return report

    def _deduplicate(self, findings: list[dict]) -> list[dict]:
        """Remove near-duplicate findings by category."""
        seen = set()
        result = []
        for f in findings:
            key = (f.get("category", ""), f.get("severity", ""))
            if key not in seen:
                seen.add(key)
                result.append(f)
        return result

    def _generate_recommendations(self, findings: list[dict]) -> list[str]:
        """Generate a prioritized list of high-level recommendations."""
        recs = []
        seen_cats = set()

        for f in findings:
            sev = f.get("severity", "").upper()
            cat = f.get("category", "")
            if sev in ("CRITICAL", "HIGH") and cat not in seen_cats:
                rec = f.get("recommendation") or f"Address {cat} vulnerability immediately"
                recs.append(f"[{sev}] {rec}")
                seen_cats.add(cat)

        if not recs:
            recs.append("No critical or high severity issues found. Review medium findings before mainnet deployment.")

        recs.append("Consider a manual audit by a qualified security firm before handling significant value.")
        recs.append("Implement comprehensive test coverage including edge cases and attack scenarios.")
        recs.append("Set up ongoing monitoring via a service like Tenderly or OpenZeppelin Defender.")

        return recs
